version: '3.8'

services:
  # Aplicação principal
  payment-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - STRIPE_SECRET_KEY=sk_test_51H1234567890abcdefghijklmnopqrstuvwxyz
      - STRIPE_PUBLISHABLE_KEY=pk_test_51H1234567890abcdefghijklmnopqrstuvwxyz
      - STRIPE_WEBHOOK_SECRET=whsec_test_1234567890abcdefghijklmnopqrstuvwxyz
      - DATABASE_URL=jdbc:postgresql://postgres:5432/moturial_payments
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres123
      - JWT_SECRET=your-256-bit-secret-key-here-change-in-production
      - SECURITY_USER_NAME=admin
      - SECURITY_USER_PASSWORD=admin123
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173
    depends_on:
      - postgres
    networks:
      - moturial-network
    restart: unless-stopped

  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=moturial_payments
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - moturial-network
    restart: unless-stopped

  # Redis para cache (opcional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - moturial-network
    restart: unless-stopped

  # pgAdmin para gerenciamento do banco (opcional)
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@moturial.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - moturial-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  moturial-network:
    driver: bridge
