spring:
  application:
    name: moturial-payment-service
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:testdb}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: ${DATABASE_DRIVER:org.h2.Driver}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:10}
      minimum-idle: ${DB_POOL_MIN_IDLE:5}
      connection-timeout: ${DB_CONNECTION_TIMEOUT:30000}
      idle-timeout: ${DB_IDLE_TIMEOUT:600000}
      max-lifetime: ${DB_MAX_LIFETIME:1800000}
  
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.H2Dialect}
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:true}
    locations: classpath:db/migration
    validate-on-migrate: ${FLYWAY_VALIDATE_ON_MIGRATE:true}
  
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:false}
  
  security:
    user:
      name: ${SECURITY_USER_NAME:admin}
      password: ${SECURITY_USER_PASSWORD:admin123}

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api/v1}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: ${HEALTH_SHOW_DETAILS:never}

stripe:
  secret-key: ${STRIPE_SECRET_KEY:sk_test_51H1234567890abcdefghijklmnopqrstuvwxyz}
  publishable-key: ${STRIPE_PUBLISHABLE_KEY:pk_test_51H1234567890abcdefghijklmnopqrstuvwxyz}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET:whsec_test_1234567890abcdefghijklmnopqrstuvwxyz}
  currency: ${STRIPE_CURRENCY:BRL}
  payment-methods:
    card: true
    pix: true
    boleto: true

logging:
  level:
    com.moturial.payment: ${LOG_LEVEL:INFO}
    com.stripe: ${STRIPE_LOG_LEVEL:WARN}
    org.springframework.security: ${SECURITY_LOG_LEVEL:WARN}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

moturial:
  security:
    api:
    key: ${API_KEY:moturial-secret-key-dev-5a7b9c1d2e3f4g5h6j7k8l9m0n1o2p3q}
  jwt:
    secret: ${JWT_SECRET:your-256-bit-secret-key-here-change-in-production}
    expiration: ${JWT_EXPIRATION:86400000}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}
    allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}
    allowed-headers: ${CORS_ALLOWED_HEADERS:*}
    allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}

payment:
  validation:
    card-number-pattern: "^[0-9]{13,19}$"
    cvv-pattern: "^[0-9]{3,4}$"
    expiry-pattern: "^(0[1-9]|1[0-2])/([0-9]{2})$"
  limits:
    max-amount: ${MAX_PAYMENT_AMOUNT:1000000}
    min-amount: ${MIN_PAYMENT_AMOUNT:100}
    max-installments: ${MAX_INSTALLMENTS:12}
  retry:
    max-attempts: ${PAYMENT_RETRY_MAX_ATTEMPTS:3}
    backoff-delay: ${PAYMENT_RETRY_BACKOFF_DELAY:1000}
