// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unfrwqpmybpgyfhfiory.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVuZnJ3cXBteWJwZ3lmaGZpb3J5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MjI4MTksImV4cCI6MjA3MTI5ODgxOX0.KV0K0FLuOOxwcJH4jLd9sdtti4Cpu9yvBE6hnDROoVg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});